// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://vwfhtpzwnrogobvggtrr.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ3Zmh0cHp3bnJvZ29idmdndHJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjkzMjY2NTksImV4cCI6MjA0NDkwMjY1OX0.pold_prB-sZ0nR_7evvQ1AoL3XaF-oHBBecFSoRsYrk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);